spring.application.name=backend
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-2f2c9a9f-esit-pos-db.g.aivencloud.com:26611/defaultdb?sslMode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_A_ChlpiSp3r2F6mRgJR}

